"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class OMEMOMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    N_FIELD_NUMBER: _builtins.int
    PN_FIELD_NUMBER: _builtins.int
    DH_PUB_FIELD_NUMBER: _builtins.int
    CIPHERTEXT_FIELD_NUMBER: _builtins.int
    n: _builtins.int
    pn: _builtins.int
    dh_pub: _builtins.bytes
    ciphertext: _builtins.bytes
    def __init__(
        self,
        *,
        n: _builtins.int | None = ...,
        pn: _builtins.int | None = ...,
        dh_pub: _builtins.bytes | None = ...,
        ciphertext: _builtins.bytes | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ciphertext", b"ciphertext", "dh_pub", b"dh_pub", "n", b"n", "pn", b"pn"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ciphertext", b"ciphertext", "dh_pub", b"dh_pub", "n", b"n", "pn", b"pn"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___OMEMOMessage: _TypeAlias = OMEMOMessage  # noqa: Y015

@_typing.final
class OMEMOAuthenticatedMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MAC_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    mac: _builtins.bytes
    message: _builtins.bytes
    """Byte-encoding of an OMEMOMessage"""
    def __init__(
        self,
        *,
        mac: _builtins.bytes | None = ...,
        message: _builtins.bytes | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["mac", b"mac", "message", b"message"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["mac", b"mac", "message", b"message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___OMEMOAuthenticatedMessage: _TypeAlias = OMEMOAuthenticatedMessage  # noqa: Y015

@_typing.final
class OMEMOKeyExchange(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PK_ID_FIELD_NUMBER: _builtins.int
    SPK_ID_FIELD_NUMBER: _builtins.int
    IK_FIELD_NUMBER: _builtins.int
    EK_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    pk_id: _builtins.int
    spk_id: _builtins.int
    ik: _builtins.bytes
    ek: _builtins.bytes
    @_builtins.property
    def message(self) -> Global___OMEMOAuthenticatedMessage: ...
    def __init__(
        self,
        *,
        pk_id: _builtins.int | None = ...,
        spk_id: _builtins.int | None = ...,
        ik: _builtins.bytes | None = ...,
        ek: _builtins.bytes | None = ...,
        message: Global___OMEMOAuthenticatedMessage | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ek", b"ek", "ik", b"ik", "message", b"message", "pk_id", b"pk_id", "spk_id", b"spk_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ek", b"ek", "ik", b"ik", "message", b"message", "pk_id", b"pk_id", "spk_id", b"spk_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___OMEMOKeyExchange: _TypeAlias = OMEMOKeyExchange  # noqa: Y015
